version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t /tmp/lib
      - ls /tmp/lib

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd /tmp/lib
      - zip -r9 /tmp/deployment_package.zip .
      - cd $CODEBUILD_SRC_DIR
      - zip -g /tmp/deployment_package.zip lambda_function.py

  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name CICD-demo --zip-file fileb:///tmp/deployment_package.zip
      - echo "DONE!!"