version: 0.2
phases:
  install:
    runtime-versions:  #Especificamos uno o mas runtimes, sino se usaran las que tiene la plataforma por defecto
      #java: corretto8
      #python: 3.x
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib
      - pwd
      - ls lib
  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
  post_build:
    commands:
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name CICD-demo --zip-file fileb://deployment_package.zip
      - echo "DONE!!"